<a href="https://colab.research.google.com/github/pociosx/stock-analysis/blob/main/stock_analysis.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import os
!git clone https://github.com/phamdinhkhanh/vnquant
os.chdir('vnquant')
!python setup.py install

fatal: destination path 'vnquant' already exists and is not an empty directory.
python3: can't open file 'setup.py': [Errno 2] No such file or directory

In [4]:
from numpy.lib.npyio import load
import pandas as pd
import datetime as dt
import pandas_datareader.data as web
from pandas import Series, DataFrame
from vnquant.DataLoader import DataLoader
import matplotlib.pyplot as plt

start = dt.datetime(2021, 1, 1)
end = dt.datetime(2021, 6, 1)

data_netflix = web.DataReader("NFLX", 'yahoo', start, end)
data_netflix.tail()

2021-06-06 15:46:31,171 : INFO : NumExpr defaulting to 2 threads.

                  High         Low        Open       Close   Volume   Adj Close
Date
2021-05-25  506.369995  499.220001  506.000000  501.339996  2699500  501.339996
2021-05-26  504.140015  500.500000  502.339996  502.359985  2465300  502.359985
2021-05-27  505.100006  498.540009  501.799988  503.859985  3253800  503.859985
2021-05-28  511.760010  502.529999  504.399994  502.809998  2910300  502.809998
2021-06-01  505.410004  497.739990  504.010010  499.079987  2482600  499.079987

In [8]:
loader = DataLoader(symbols='VIC',
                    start='2021-01-01',
                    end='2021-06-01',
                    minimal=False,
                    data_source='vnd')

data_vic = loader.download()
data_vic.head()

2021-06-06 15:48:01,173 : INFO : data VIC from 2021-01-01 to 2021-06-01 have already cloned!

Attributes adjust  close change_perc     avg  ...   open   high    low     volume
Symbols       VIC    VIC         VIC     VIC  ...    VIC    VIC    VIC        VIC
date                                          ...
2021-01-04  108.0  108.0     -0.1848  108.52  ...  108.5  109.0  106.5   991100.0
2021-01-05  109.7  109.7      1.5741  108.63  ...  107.2  109.9  107.2  1192200.0
2021-01-06  110.2  110.2      0.4558  109.98  ...  110.0  110.5  108.9  1415800.0
2021-01-07  110.1  110.1     -0.0907  110.33  ...  110.4  111.0  109.0  1382900.0
2021-01-08  111.8  111.8      1.5441  111.87  ...  110.1  112.7  110.1  1577500.0

[5 rows x 12 columns]

In [7]:
loader = DataLoader(symbols='HVN',
                    start='2021-01-01',
                    end='2021-06-01',
                    minimal=False,
                    data_source='vnd')
data_hvn = loader.download()
data_hvn.tail()

2021-06-06 15:47:55,878 : INFO : data HVN from 2021-01-01 to 2021-06-01 have already cloned!

Attributes adjust  close change_perc    avg  ...  open   high    low     volume
Symbols       HVN    HVN         HVN    HVN  ...   HVN    HVN    HVN        HVN
date                                         ...
2021-05-26  26.50  26.50     -0.7491  26.50  ...  26.7  26.90  26.20   625600.0
2021-05-27  26.10  26.10     -1.5094  26.24  ...  26.4  26.50  26.00  1393900.0
2021-05-28  26.20  26.20      0.3831  26.20  ...  26.1  26.40  26.05  1288800.0
2021-05-31  25.85  25.85     -1.3359  25.87  ...  26.0  26.15  25.80   707200.0
2021-06-01  25.65  25.65     -0.7737  25.78  ...  25.8  25.85  25.60  1036100.0

[5 rows x 12 columns]